[directory]
truncation_length = 0
truncate_to_repo = false
style = "bold blue"
repo_root_style = "bold white" 

[character]
# error_symbol = "[Xâ¯](bold red)"

[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[git_branch]
# symbol = "ğŸŒ¿ "

[line_break]
# disabled = true

[status]
disabled = true

[python]
version_format = "v${major}.${minor}"

[shlvl]
# disabled = false
symbol = "â†•"

[sudo]
disabled = true
format = '[$symbol]($style)'
symbol = 'ğŸ›¡ï¸'

[erlang]
symbol = "â“” "

[nodejs]
symbol = "[â¬¢](bold green) "

[pulumi]
symbol = "ğŸ§Š "

[typst]
symbol = "t "

